name: Build theme and release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the theme'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Prepare for jar
        shell: bash
        run: |
          mkdir theme
          cp -r luna-theme/ theme/
      - name: Build theme JAR
        run: jar cvf luna-theme.jar META-INF/* theme/luna-theme/*
      - name: Generate release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create ${{ inputs.version }} luna-theme.jar
        
